### ISSUE TITLE
unable to Launch the project with the "sawr/catkin_ws/src/sawr/sawr_master$ LAUNCH.md"

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [01org/sawr#4]
Hi,

I am planning to use this package, I am able to make and install the package but when i try to launch the package i get a error. 

DL:~/github/sawr/catkin_ws/src/sawr/sawr_master$ ./LAUNCH.md
./LAUNCH.md: line 1: syntax error near unexpected token `('
./LAUNCH.md: line 1: `Simple Autonomous Wheeled Robot (SAWR)'

Can you please help me fix this.

Regards,
SSH

**Comment by mmccool** [comment]
This is an md, or MarkDown file.  It's documentation, not an executable.  Please look at it on github where it will be rendered properly: https://github.com/01org/sawr/blob/master/sawr_master/LAUNCH.md

**Comment by ShettyHarapanahalli** [comment]
Thanks, i was able to launch !!
